### ISSUE TITLE
Setup changelog support

### ISSUE THREAD

**Issue by christoff-linde** [SchizzY/next-month-web#4]
### Description

To help keep track of contributors & version updates, a changelog feature/flow should be implemented.

One option would be to follow semantic versioning, supported by GitHub Actions to automatically update changelogs, create releases, etc.

The full scope & requirements for this process should be scoped out and finalised.

### Task List

- [ ] Workshop changelog convention/standard
- [ ] Investigate implementation/requirements for semantic versioning
- [ ] Implement pipelines for releases, changelogs, etc.
